import type { LucideIconData } from 'lucide-angular';
import {
  Award,
  ArrowRight,
  ArrowUpRight,
  AlertCircle,
  Check,
  CheckCircle2,
  ChevronDown,
  Clock,
  Cloud,
  Code2,
  Compass,
  Cpu,
  Database,
  Facebook,
  Github,
  Globe,
  HeartHandshake,
  Layers,
  LifeBuoy,
  Loader2,
  Lock,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  MonitorSmartphone,
  Moon,
  Network,
  Phone,
  Rocket,
  Send,
  Shield,
  Sparkles,
  Sun,
  Target,
  Users,
  Workflow,
  X,
  Linkedin,
  Twitter,
  Youtube,
} from 'lucide-angular';

/** Maps a PascalCase icon key to its kebab-case equivalent ('MapPin' -> 'map-pin'). */
function toKebab(name: string): string {
  return name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}

const RAW_ICONS: Record<string, LucideIconData> = {
  Award,
  ArrowRight,
  ArrowUpRight,
  AlertCircle,
  Check,
  CheckCircle2,
  ChevronDown,
  Clock,
  Cloud,
  Code2,
  Compass,
  Cpu,
  Database,
  Facebook,
  Github,
  Globe,
  HeartHandshake,
  Layers,
  LifeBuoy,
  Loader2,
  Lock,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  MonitorSmartphone,
  Moon,
  Network,
  Phone,
  Rocket,
  Send,
  Shield,
  Sparkles,
  Sun,
  Target,
  Users,
  Workflow,
  X,
  Linkedin,
  Twitter,
  Youtube,
};

/**
 * Lookup table accepting both PascalCase ('MapPin') and kebab-case ('map-pin')
 * keys — templates and i18n data reference icons in kebab-case.
 */
export const FLUIDITY_ICONS: Record<string, LucideIconData> = Object.fromEntries(
  Object.entries(RAW_ICONS).flatMap(([key, icon]) => [
    [key, icon],
    [toKebab(key), icon],
  ]),
);
